-- GF-4, step 1 of 2: tracked-device and location-event tables.
--
-- Generated by `prisma migrate dev --create-only`, then edited by hand for one
-- reason, recorded here in full:
--
--   Prisma emitted a leading
--     ALTER TABLE "Geofence" ALTER COLUMN "centerPoint" DROP NOT NULL,
--     ALTER COLUMN "centerPoint" DROP DEFAULT;
--   block and it was REMOVED.
--
--   That block is not a GF-4 change. It is Prisma re-proposing the known,
--   documented GF-3 drift: Prisma models "centerPoint" as an optional
--   `Unsupported(...)` field and cannot represent a STORED GENERATED column, so
--   on every schema change it offers to strip the NOT NULL and the generation
--   expression that make scalar/spatial divergence impossible. PostgreSQL
--   refuses the statement outright ("column is a generated column"), which is
--   how the shadow-database run surfaced it. Keeping it would have silently
--   reverted the GF-3 spatial guarantee if it had ever succeeded.
--
--   The drift itself is unchanged and still asserted verbatim by
--   scripts/disposable-db-test.mjs; it is not suppressed, only kept out of a
--   migration that has nothing to do with it.
--
-- Everything below is Prisma's own output, unmodified. "observedPoint" appears
-- here as a plain nullable geography column because that is the most Prisma can
-- express for an `Unsupported(...)` field; the next migration replaces it with a
-- generated column and adds the CHECK constraints.

-- CreateTable
CREATE TABLE "TrackedDevice" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "deviceKey" VARCHAR(128) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TrackedDevice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LocationEvent" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "trackedDeviceId" TEXT NOT NULL,
    "eventKey" VARCHAR(200) NOT NULL,
    "observedAt" TIMESTAMPTZ(3) NOT NULL,
    "receivedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "accuracyMeters" DOUBLE PRECISION NOT NULL,
    "observedPoint" geography(Point, 4326),

    CONSTRAINT "LocationEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TrackedDevice_tenantId_idx" ON "TrackedDevice"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "TrackedDevice_tenantId_deviceKey_key" ON "TrackedDevice"("tenantId", "deviceKey");

-- CreateIndex
CREATE UNIQUE INDEX "TrackedDevice_id_tenantId_key" ON "TrackedDevice"("id", "tenantId");

-- CreateIndex
CREATE INDEX "LocationEvent_tenantId_trackedDeviceId_observedAt_idx" ON "LocationEvent"("tenantId", "trackedDeviceId", "observedAt");

-- CreateIndex
CREATE UNIQUE INDEX "LocationEvent_tenantId_trackedDeviceId_eventKey_key" ON "LocationEvent"("tenantId", "trackedDeviceId", "eventKey");

-- AddForeignKey
ALTER TABLE "TrackedDevice" ADD CONSTRAINT "TrackedDevice_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LocationEvent" ADD CONSTRAINT "LocationEvent_trackedDeviceId_tenantId_fkey" FOREIGN KEY ("trackedDeviceId", "tenantId") REFERENCES "TrackedDevice"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;
