-- GF-6: deterministic geofence transition state.
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema`
-- against the migrated disposable database, then edited by hand for one reason,
-- recorded here in full:
--
--   Prisma emitted
--     ALTER TABLE "Geofence" ALTER COLUMN "centerPoint" DROP NOT NULL,
--       ALTER COLUMN "centerPoint" DROP DEFAULT;
--     ALTER TABLE "LocationEvent" ALTER COLUMN "observedPoint" DROP NOT NULL,
--       ALTER COLUMN "observedPoint" DROP DEFAULT;
--   and both blocks were REMOVED.
--
--   Neither is a GF-6 change. They are the known, documented GF-3/GF-4 drift:
--   Prisma models the geography columns as optional `Unsupported(...)` fields
--   and cannot represent a STORED GENERATED column, so on every schema change it
--   re-proposes stripping the NOT NULL and the generation expression that make
--   scalar/spatial divergence impossible. PostgreSQL refuses the statement
--   outright ("column is a generated column"). The same removal was made, for
--   the same reason, in the GF-4 `tracked_devices_and_location_events`
--   migration; the drift is still asserted verbatim by
--   scripts/disposable-db-test.mjs and is not suppressed here, only kept out of
--   a migration that has nothing to do with it.
--
-- Everything below is Prisma's own output, unmodified.

-- CreateEnum
CREATE TYPE "GeofenceContainmentState" AS ENUM ('INSIDE', 'OUTSIDE');

-- CreateEnum
CREATE TYPE "GeofenceTransition" AS ENUM ('BASELINE_INSIDE', 'BASELINE_OUTSIDE', 'ENTER', 'EXIT', 'STAY_INSIDE', 'STAY_OUTSIDE');

-- CreateTable
CREATE TABLE "GeofenceDeviceState" (
    "tenantId" TEXT NOT NULL,
    "trackedDeviceId" TEXT NOT NULL,
    "geofenceId" TEXT NOT NULL,
    "state" "GeofenceContainmentState" NOT NULL,
    "lastTransition" "GeofenceTransition" NOT NULL,
    "lastLocationEventId" TEXT NOT NULL,
    "lastObservedAt" TIMESTAMPTZ(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GeofenceDeviceState_pkey" PRIMARY KEY ("tenantId","trackedDeviceId","geofenceId")
);

-- CreateIndex
CREATE INDEX "GeofenceDeviceState_tenantId_geofenceId_idx" ON "GeofenceDeviceState"("tenantId", "geofenceId");

-- CreateIndex
CREATE INDEX "GeofenceDeviceState_tenantId_lastLocationEventId_idx" ON "GeofenceDeviceState"("tenantId", "lastLocationEventId");

-- CreateIndex
CREATE UNIQUE INDEX "Geofence_id_tenantId_key" ON "Geofence"("id", "tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "LocationEvent_id_tenantId_key" ON "LocationEvent"("id", "tenantId");

-- AddForeignKey
ALTER TABLE "GeofenceDeviceState" ADD CONSTRAINT "GeofenceDeviceState_trackedDeviceId_tenantId_fkey" FOREIGN KEY ("trackedDeviceId", "tenantId") REFERENCES "TrackedDevice"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeofenceDeviceState" ADD CONSTRAINT "GeofenceDeviceState_geofenceId_tenantId_fkey" FOREIGN KEY ("geofenceId", "tenantId") REFERENCES "Geofence"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeofenceDeviceState" ADD CONSTRAINT "GeofenceDeviceState_lastLocationEventId_tenantId_fkey" FOREIGN KEY ("lastLocationEventId", "tenantId") REFERENCES "LocationEvent"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;
