-- GF-7: deterministic geofence alert events.
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema`
-- against the migrated disposable database, then edited by hand for two
-- reasons, both recorded here in full:
--
--   1. Prisma emitted
--        ALTER TABLE "Geofence" ALTER COLUMN "centerPoint" DROP NOT NULL,
--          ALTER COLUMN "centerPoint" DROP DEFAULT;
--        ALTER TABLE "LocationEvent" ALTER COLUMN "observedPoint" DROP NOT NULL,
--          ALTER COLUMN "observedPoint" DROP DEFAULT;
--      and both blocks were REMOVED.
--
--      Neither is a GF-7 change. They are the known, documented GF-3/GF-4 drift:
--      Prisma models the geography columns as optional `Unsupported(...)` fields
--      and cannot represent a STORED GENERATED column, so on every schema change
--      it re-proposes stripping the NOT NULL and the generation expression that
--      make scalar/spatial divergence impossible. PostgreSQL refuses the
--      statement outright ("column is a generated column"). The same removal was
--      made, for the same reason, in the GF-4
--      `tracked_devices_and_location_events` and GF-6
--      `geofence_device_transition_state` migrations; the drift is still
--      asserted verbatim by scripts/disposable-db-test.mjs and is not suppressed
--      here, only kept out of a migration that has nothing to do with it.
--
--   2. The `AlertEvent_transition_crossing_check` CHECK constraint at the end was
--      ADDED by hand. Prisma has no way to declare a CHECK constraint in the
--      schema, and it does not read them back either, so this addition creates no
--      drift. It restricts transition labels to ENTER/EXIT, not spatial history.
--      Direct SQL can fabricate an allowed label; application classification
--      and the shared transaction establish genuine crossing semantics.
--
-- Everything else below is Prisma's own output, unmodified.
--
-- The five new columns are NOT NULL without a backfill default, which is safe
-- only when the legacy table is empty. The repository had no production writer,
-- but that does not prove deployed database contents. Verify this precondition
-- before deployment. If an environment contains a legacy row, this statement fails
-- loudly instead of inventing a tenant, a device or an observation time for it,
-- which is the correct outcome.

-- DropForeignKey
--
-- Replaced, in this same migration, by the composite
-- (geofenceId, tenantId) -> Geofence(id, tenantId) key below. That key enforces
-- everything this one did and additionally makes an alert whose tenant disagrees
-- with its geofence's tenant impossible to store, so this is a strictly stronger
-- constraint rather than a relaxation.
ALTER TABLE "AlertEvent" DROP CONSTRAINT "AlertEvent_geofenceId_fkey";

-- AlterTable
ALTER TABLE "AlertEvent" ADD COLUMN     "observedAt" TIMESTAMPTZ(3) NOT NULL,
ADD COLUMN     "sourceLocationEventId" TEXT NOT NULL,
ADD COLUMN     "tenantId" TEXT NOT NULL,
ADD COLUMN     "trackedDeviceId" TEXT NOT NULL,
ADD COLUMN     "transition" "GeofenceTransition" NOT NULL,
ALTER COLUMN "eventType" DROP NOT NULL,
ALTER COLUMN "message" DROP NOT NULL;

-- CreateIndex
CREATE INDEX "AlertEvent_tenantId_sourceLocationEventId_idx" ON "AlertEvent"("tenantId", "sourceLocationEventId");

-- CreateIndex
CREATE INDEX "AlertEvent_tenantId_geofenceId_idx" ON "AlertEvent"("tenantId", "geofenceId");

-- CreateIndex
CREATE UNIQUE INDEX "AlertEvent_crossing_key" ON "AlertEvent"("tenantId", "trackedDeviceId", "geofenceId", "sourceLocationEventId", "transition");

-- AddForeignKey
ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_geofenceId_tenantId_fkey" FOREIGN KEY ("geofenceId", "tenantId") REFERENCES "Geofence"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_trackedDeviceId_tenantId_fkey" FOREIGN KEY ("trackedDeviceId", "tenantId") REFERENCES "TrackedDevice"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_sourceLocationEventId_tenantId_fkey" FOREIGN KEY ("sourceLocationEventId", "tenantId") REFERENCES "LocationEvent"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddCheckConstraint (hand-written; see note 2 above)
--
-- BASELINE_INSIDE, BASELINE_OUTSIDE, STAY_INSIDE and STAY_OUTSIDE are not
-- crossings. A baseline is the first thing known about a device's position, not
-- evidence that it moved; a stay is evidence that it did not. Only ENTER and
-- EXIT are boundary crossings, and only a boundary crossing is an alert.
ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_transition_crossing_check"
  CHECK ("transition" IN ('ENTER', 'EXIT'));
